# Generated by Django 2.2.3 on 2019-07-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(default='', max_length=50)),
                ('date_event', models.DateField(default='', max_length=150)),
                ('cost', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoName', models.CharField(default='', max_length=50)),
                ('terminos', models.CharField(default='', max_length=150)),
                ('media', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=150)),
                ('comunidad', models.CharField(default='', max_length=150)),
                ('grupo', models.CharField(default='', max_length=150)),
                ('grupoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GrupoName')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('date_anuncio', models.DateField(default='', max_length=150)),
                ('evento_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Evento')),
                ('votante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ubication', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=150)),
                ('comuna_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Comuna')),
                ('pais_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pais')),
                ('region_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region')),
                ('ubication_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rol', models.CharField(default='', max_length=50)),
                ('miembro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro'),
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo_nameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GrupoName'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ubicacion'),
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncioName', models.CharField(default='', max_length=50)),
                ('descripton', models.CharField(default='', max_length=150)),
                ('media', models.CharField(default='', max_length=150)),
                ('date_anuncio', models.DateField(default='', max_length=150)),
                ('ubication', models.CharField(default='', max_length=150)),
                ('anuncio_nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro')),
            ],
        ),
    ]
