# Generated by Django 2.2.3 on 2019-07-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190726_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='grupoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GrupoName'),
        ),
    ]
