# Generated by Django 2.2.3 on 2019-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190726_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='date_anuncio',
            field=models.DateField(default='', max_length=150, null=True),
        ),
    ]
