# Generated by Django 2.2.3 on 2019-08-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190729_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo_nameID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GrupoName'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ubicacion'),
        ),
    ]
