# Generated by Django 2.2.4 on 2019-08-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190806_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='comunidad',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='grupo',
        ),
    ]
