# Generated by Django 2.2.4 on 2019-08-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190820_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='grupoid',
        ),
        migrations.AddField(
            model_name='miembro',
            name='gruponame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruponame', to='api.GrupoName'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='date_anuncio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='date_event',
            field=models.DateField(),
        ),
    ]
