# Generated by Django 2.2.4 on 2019-08-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190822_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='gruponame_id',
            new_name='gruponame',
        ),
    ]
