# Generated by Django 2.2.4 on 2019-08-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190822_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruponame',
            name='grupoName',
            field=models.CharField(max_length=50),
        ),
    ]
